### ISSUE TITLE
Front end is not running

### ISSUE THREAD

**Issue by officeabg** [JarrodMalkovic/auction-website#1]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

- **Do you want to request a _feature_ or report a _bug_?**

- **What is the current behavior?**
- After a clean install nothing happens. The front end is nowhere to be found.

- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
- Clean installations no errors and still app is not running

- **What is the expected behavior?**
- Find front end on localhost:3000

- **What is the motivation / use case for changing the behavior?**

- **Please tell us about your environment:**

  - Version: 2.0.0-beta.X
  - Language: [ TypeScript X.X | ES6/7 | ES5 | Dart]
  - Node: 11.3.2 and 14.x.x

- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

I have rebuilt every docker image and fixed some errors asking for jwt-secret instead of jwt-key-secret and stripe-secret instead of stripe-key-secret. After that skaffold is running without error. Here the scaffold build output.

$ skaffold dev
Listing files to watch...
 - officeabg/auction-website-auth
 - officeabg/auction-website-listings
 - officeabg/auction-website-bid
 - officeabg/auction-website-expiration
 - officeabg/auction-website-profile
 - officeabg/auction-website-frontend
 - officeabg/auction-website-email
 - officeabg/auction-website-payments
Generating tags...
 - officeabg/auction-website-auth -> officeabg/auction-website-auth:0ed78bc
 - officeabg/auction-website-listings -> officeabg/auction-website-listings:0ed78bc
 - officeabg/auction-website-bid -> officeabg/auction-website-bid:0ed78bc
 - officeabg/auction-website-expiration -> officeabg/auction-website-expiration:0ed78bc
 - officeabg/auction-website-profile -> officeabg/auction-website-profile:0ed78bc
 - officeabg/auction-website-frontend -> officeabg/auction-website-frontend:0ed78bc
 - officeabg/auction-website-email -> officeabg/auction-website-email:0ed78bc
 - officeabg/auction-website-payments -> officeabg/auction-website-payments:0ed78bc
Checking cache...
 - officeabg/auction-website-auth: Found Locally
 - officeabg/auction-website-listings: Found Locally
 - officeabg/auction-website-bid: Found Locally
 - officeabg/auction-website-expiration: Found Locally
 - officeabg/auction-website-profile: Found Locally
 - officeabg/auction-website-frontend: Found Locally
 - officeabg/auction-website-email: Found Locally
 - officeabg/auction-website-payments: Found Locally
Starting test...
Tags used in deployment:
 - officeabg/auction-website-auth -> officeabg/auction-website-auth:962b62f34752c31e18bdc8b8c0f7f020147dee40fed177344375a4be0ac9f5cb
 - officeabg/auction-website-listings -> officeabg/auction-website-listings:2171b428a626148e69453ee17aeac9b2c71007270167ef80452501ef37fa57ea
 - officeabg/auction-website-bid -> officeabg/auction-website-bid:ace2e94cb0374453e596175d099433d4941a70e0fb59c3c71288e1904b1e1063
 - officeabg/auction-website-expiration -> officeabg/auction-website-expiration:4c293e4dbe6515c5badc3aa795194f4a13cfbd90045e8dcd3d6942697a76a155
 - officeabg/auction-website-profile -> officeabg/auction-website-profile:ac7b981ce703d86e63ee1979472a9ca206c4242e897eca1d95cb5d6be100ee1c
 - officeabg/auction-website-frontend -> officeabg/auction-website-frontend:0fcde0e2159832aef46f75ee5ed1a85092009d2cad64b1c536f8562555d30089
 - officeabg/auction-website-email -> officeabg/auction-website-email:7a5e3c13274ec455a86600ffee8cbabf3dff619056837e0c4fe38f2d4ac9c863
 - officeabg/auction-website-payments -> officeabg/auction-website-payments:0e17462a0a990d5bda8891a7672637bb3b3f5ff29543f221fe276485ee60e07e
Starting deploy...
 - deployment.apps/auth-depl configured
 - service/auth-srv configured
 - deployment.apps/auth-mysql-depl configured
 - service/auth-mysql-srv configured
 - deployment.apps/bid-depl configured
 - service/bid-srv configured
 - deployment.apps/bid-mysql-depl configured
 - service/bid-mysql-srv configured
 - deployment.apps/email-depl configured
 - deployment.apps/expiration-depl configured
 - deployment.apps/expiration-redis-depl configured
 - service/expiration-redis-srv configured
 - deployment.apps/frontend-depl configured
 - service/frontend-srv configured
 - ingress.networking.k8s.io/ingress-srv configured
 - deployment.apps/listings-depl configured
 - service/listings-srv configured
 - deployment.apps/listings-mysql-depl configured
 - service/listings-mysql-srv configured
 - deployment.apps/nats-depl configured
 - service/nats-srv configured
 - deployment.apps/payments-depl configured
 - service/payments-srv configured
 - deployment.apps/payments-mysql-depl configured
 - service/payments-mysql-srv configured
 - deployment.apps/profile-depl configured
 - service/profile-srv configured
 - deployment.apps/profile-mysql-depl configured
 - service/profile-mysql-srv configured
Waiting for deployments to stabilize...
 - deployment/bid-depl is ready. [14/15 deployment(s) still pending]
 - deployment/email-depl is ready. [13/15 deployment(s) still pending]
 - deployment/expiration-depl is ready. [12/15 deployment(s) still pending]
 - deployment/auth-mysql-depl: waiting for rollout to finish: 0 out of 1 new replicas have been updated...
 - deployment/bid-mysql-depl: waiting for rollout to finish: 0 of 1 updated replicas are available...
 - deployment/expiration-redis-depl: creating container expiration-redis
    - pod/expiration-redis-depl-698bc9946f-wrhb6: creating container expiration-redis
 - deployment/frontend-depl: waiting for rollout to finish: 1 old replicas are pending termination...
 - deployment/listings-depl: waiting for rollout to finish: 1 old replicas are pending termination...
 - deployment/listings-mysql-depl: waiting for rollout to finish: 0 of 1 updated replicas are available...
 - deployment/nats-depl: creating container nats
    - pod/nats-depl-7b6bcd6cc7-9wdh8: creating container nats
 - deployment/payments-depl: creating container payments
    - pod/payments-depl-8f4f8bbf8-7gtw4: creating container payments
 - deployment/payments-mysql-depl: waiting for rollout to finish: 0 out of 1 new replicas have been updated...
 - deployment/profile-depl: waiting for rollout to finish: 1 old replicas are pending termination...
 - deployment/profile-mysql-depl: waiting for rollout to finish: 0 out of 1 new replicas have been updated...
 - deployment/auth-depl is ready. [11/15 deployment(s) still pending]
 - deployment/auth-mysql-depl: waiting for rollout to finish: 0 out of 1 new replicas have been updated...
 - deployment/bid-mysql-depl: waiting for rollout to finish: 0 of 1 updated replicas are available...
 - deployment/expiration-redis-depl: creating container expiration-redis
    - pod/expiration-redis-depl-698bc9946f-wrhb6: creating container expiration-redis
 - deployment/frontend-depl: waiting for rollout to finish: 1 old replicas are pending termination...
 - deployment/listings-depl: waiting for rollout to finish: 1 old replicas are pending termination...
 - deployment/listings-mysql-depl: waiting for rollout to finish: 0 of 1 updated replicas are available...
 - deployment/nats-depl: creating container nats
    - pod/nats-depl-7b6bcd6cc7-9wdh8: creating container nats
 - deployment/profile-depl: waiting for rollout to finish: 1 old replicas are pending termination...
 - deployment/auth-mysql-depl: waiting for rollout to finish: 0 out of 1 new replicas have been updated...
 - deployment/bid-mysql-depl: waiting for rollout to finish: 0 of 1 updated replicas are available...
 - deployment/expiration-redis-depl: creating container expiration-redis
    - pod/expiration-redis-depl-698bc9946f-wrhb6: creating container expiration-redis
 - deployment/frontend-depl: waiting for rollout to finish: 1 old replicas are pending termination...
 - deployment/expiration-redis-depl: waiting for rollout to finish: 1 old replicas are pending termination...
 - deployment/expiration-redis-depl: waiting for rollout to finish: 1 old replicas are pending termination...
 - deployment/auth-mysql-depl: waiting for rollout to finish: 0 of 1 updated replicas are available...
 - deployment/listings-depl is ready. [10/15 deployment(s) still pending]
 - deployment/expiration-redis-depl is ready. [9/15 deployment(s) still pending]
 - deployment/frontend-depl is ready. [8/15 deployment(s) still pending]
 - deployment/payments-depl: waiting for rollout to finish: 1 old replicas are pending termination...
 - deployment/payments-depl: waiting for rollout to finish: 1 old replicas are pending termination...
 - deployment/payments-depl is ready. [7/15 deployment(s) still pending]
 - deployment/profile-mysql-depl: waiting for rollout to finish: 0 out of 1 new replicas have been updated...
 - deployment/profile-mysql-depl: waiting for rollout to finish: 0 of 1 updated replicas are available...
 - deployment/payments-mysql-depl: waiting for rollout to finish: 0 out of 1 new replicas have been updated...
 - deployment/payments-mysql-depl: waiting for rollout to finish: 0 of 1 updated replicas are available...
 - deployment/listings-mysql-depl is ready. [6/15 deployment(s) still pending]
 - deployment/bid-mysql-depl is ready. [5/15 deployment(s) still pending]
 - deployment/nats-depl: waiting for rollout to finish: 1 old replicas are pending termination...
 - deployment/nats-depl: waiting for rollout to finish: 1 old replicas are pending termination...
 - deployment/payments-mysql-depl is ready. [4/15 deployment(s) still pending]
 - deployment/nats-depl is ready. [3/15 deployment(s) still pending]
 - deployment/profile-depl is ready. [2/15 deployment(s) still pending]
 - deployment/auth-mysql-depl is ready. [1/15 deployment(s) still pending]
 - deployment/profile-mysql-depl is ready.
Deployments stabilized in 2 minutes 11.527 seconds
Press Ctrl+C to exit
Watching for changes...
[auth]
[auth] > auth@1.0.0 dev
[auth] > ts-node-dev src/index.ts
[auth]
[auth] [INFO] 09:43:09 ts-node-dev ver. 1.1.6 (using ts-node ver. 9.1.1, typescript ver. 4.2.4)
[payments]
[payments] > payments@1.0.0 dev
[payments] > ts-node-dev src/index.ts
[payments]
[payments] [INFO] 09:43:11 ts-node-dev ver. 1.1.6 (using ts-node ver. 9.1.1, typescript ver. 4.2.4)
[frontend]
[frontend] > frontend-service@0.1.0 dev /app
[listings]
[listings] > listings@1.0.0 dev
[listings] > ts-node-dev src/index.ts
[listings]
[listings] [INFO] 09:43:07 ts-node-dev ver. 1.1.6 (using ts-node ver. 9.1.1, typescript ver. 4.2.4)
[frontend] > next dev
[frontend]
[profile]
[profile] > profile@1.0.0 dev /app
[profile] > ts-node-dev src/index.ts
[profile]
[profile] [INFO] 09:43:21 ts-node-dev ver. 1.1.6 (using ts-node ver. 9.1.1, typescript ver. 4.2.4)
[bid]
[bid] > bid@1.0.0 dev
[bid] > ts-node-dev src/index.ts
[bid]
[bid] [INFO] 09:43:09 ts-node-dev ver. 1.1.6 (using ts-node ver. 9.1.1, typescript ver. 4.2.4)
[expiration]
[expiration] > expiration@1.0.0 dev
[expiration] > ts-node-dev src/index.ts
[expiration]
[expiration] [INFO] 09:42:57 ts-node-dev ver. 1.1.6 (using ts-node ver. 9.1.1, typescript ver. 4.2.4)
[email]
[email] > listings@1.0.0 dev /app
[email] > ts-node-dev src/index.ts
[email]
[email] [INFO] 09:42:43 ts-node-dev ver. 1.1.6 (using ts-node ver. 9.1.1, typescript ver. 4.2.4)
[frontend] Browserslist: caniuse-lite is outdated. Please run:
[frontend] npx browserslist@latest --update-db
[frontend] ready - started server on http://localhost:3000
[frontend] info  - Using external babel configuration from /app/.babelrc
[email] The profile service has started
[email] Connected to NATS
[email] The email service has started up successfully
[expiration] Connected to NATS
[profile] The profile service has started
[profile] Connected to NATS
[profile] Executing (default): SELECT 1+1 AS result
[profile] Executing (default): CREATE TABLE IF NOT EXISTS `profiles` (`id` CHAR(36) BINARY UNIQUE , `userId` CHAR(36) BINARY, `about` VARCHAR(255) NOT NULL, `firstName` VARCHAR(255) NOT NULL, `lastName` VARCHAR(255) NOT NULL, `country` VARCHAR(255) NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `version` INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (`id`)) ENGINE=InnoDB;
[profile] Executing (default): SHOW INDEX FROM `profiles`
[profile] Conneted to MySQL
[profile] The profile service has started up successfully
[profile] Listening on port 3000!
[bid] The bid service has started
[bid] Connected to NATS
[bid] Executing (default): SELECT 1+1 AS result
[bid] Executing (default): DROP TABLE IF EXISTS `bids`;
[bid] Executing (default): DROP TABLE IF EXISTS `listings`;
[bid] Executing (default): DROP TABLE IF EXISTS `users`;
[bid] Executing (default): DROP TABLE IF EXISTS `users`;
[bid] Executing (default): CREATE TABLE IF NOT EXISTS `users` (`id` CHAR(36) BINARY UNIQUE , `name` VARCHAR(255) NOT NULL UNIQUE, `email` VARCHAR(255) NOT NULL UNIQUE, `avatar` VARCHAR(255) NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `version` INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (`id`)) ENGINE=InnoDB;
[bid] Executing (default): SHOW INDEX FROM `users`
[auth] The auth service has started
[bid] Executing (default): DROP TABLE IF EXISTS `listings`;
[bid] Executing (default): CREATE TABLE IF NOT EXISTS `listings` (`id` CHAR(36) BINARY UNIQUE , `userId` CHAR(36) BINARY NOT NULL, `currentWinnerId` CHAR(36) BINARY, `status` ENUM('Active', 'Expired', 'awaiting:payment', 'complete') DEFAULT 'Active', `expiresAt` DATETIME NOT NULL, `startPrice` INTEGER NOT NULL, `currentPrice` INTEGER NOT NULL, `title` VARCHAR(255) NOT NULL, `slug` VARCHAR(255) NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `version` INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (`id`)) ENGINE=InnoDB;
[auth] Connected to NATS
[bid] Executing (default): SHOW INDEX FROM `listings`
[bid] Executing (default): DROP TABLE IF EXISTS `bids`;
[bid] Executing (default): CREATE TABLE IF NOT EXISTS `bids` (`id` CHAR(36) BINARY UNIQUE , `listingId` CHAR(36) BINARY, `userId` CHAR(36) BINARY, `amount` INTEGER NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `version` INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (`id`), FOREIGN KEY (`listingId`) REFERENCES `listings` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
[payments] The bid service has started
[bid] Executing (default): SHOW INDEX FROM `bids`
[bid] Conneted to MySQL
[bid] The auth service has started up successfully
[bid] Listening on port 3000!
[auth] Executing (default): SELECT 1+1 AS result
[payments] Connected to NATS
[auth] Conneted to MySQL
[auth] Listening on port 3000!
[auth] The auth service has started up successfully
[auth] Executing (default): CREATE TABLE IF NOT EXISTS `users` (`id` CHAR(36) BINARY UNIQUE , `email` VARCHAR(255) NOT NULL UNIQUE, `avatar` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NOT NULL UNIQUE, `password` VARCHAR(255) NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `version` INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (`id`)) ENGINE=InnoDB;
[payments] Executing (default): SELECT 1+1 AS result
[payments] Executing (default): CREATE TABLE IF NOT EXISTS `listings` (`id` CHAR(36) BINARY UNIQUE , `winnerId` CHAR(36) BINARY, `status` ENUM('Active', 'Expired', 'awaiting:payment', 'complete') DEFAULT 'Active', `amount` INTEGER NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `version` INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (`id`)) ENGINE=InnoDB;
[payments] Executing (default): SHOW INDEX FROM `listings`
[payments] Executing (default): CREATE TABLE IF NOT EXISTS `payments` (`id` CHAR(36) BINARY UNIQUE , `listingId` CHAR(36) BINARY, `stripeId` VARCHAR(255) NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `version` INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (`id`)) ENGINE=InnoDB;
[auth] Executing (default): SHOW INDEX FROM `users`
[payments] Executing (default): SHOW INDEX FROM `payments`
[payments] Conneted to MySQL
[payments] The auth service has started up successfully
[payments] Listening on port 3000!
[listings] The listings service has started
[listings] Connected to NATS
[listings] Executing (default): SELECT 1+1 AS result
[listings] Executing (default): CREATE TABLE IF NOT EXISTS `users` (`id` CHAR(36) BINARY UNIQUE , `name` VARCHAR(255) NOT NULL UNIQUE, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `version` INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (`id`)) ENGINE=InnoDB;
[listings] Executing (default): SHOW INDEX FROM `users`
[listings] Executing (default): CREATE TABLE IF NOT EXISTS `listings` (`id` CHAR(36) BINARY UNIQUE , `userId` CHAR(36) BINARY NOT NULL, `currentWinnerId` CHAR(36) BINARY DEFAULT NULL, `status` ENUM('Active', 'Expired', 'awaiting:payment', 'complete') DEFAULT 'Active', `startPrice` INTEGER NOT NULL, `currentPrice` INTEGER NOT NULL, `title` VARCHAR(255) NOT NULL, `imageId` VARCHAR(255) NOT NULL, `smallImage` VARCHAR(255) NOT NULL, `largeImage` VARCHAR(255) NOT NULL, `description` VARCHAR(255) NOT NULL, `slug` VARCHAR(255) UNIQUE, `expiresAt` DATETIME NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `version` INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (`id`), FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
[listings] Executing (default): SHOW INDEX FROM `listings`
[listings] Executing (default): ALTER TABLE `listings` ADD FULLTEXT INDEX `text_idx` (`title`)
[listings] Conneted to MySQL
[listings] The listings service has started up successfully
[listings] Listening on port 3000!
[frontend] event - compiled successfully
[frontend] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[frontend] This information is used to shape Next.js' roadmap and prioritize features.
[frontend] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[frontend] https://nextjs.org/telemetry
[frontend]

Thanks

**Comment by JarrodMalkovic** [comment]
Thanks for the report.

To access to frontend (or any API route) in this project, you need to edit your hosts file (https://phoenixnap.com/kb/how-to-edit-hosts-file-in-windows-mac-or-linux) by adding the line:

```bash
127.0.0.1 auctionweb.site
```
 
This will allow you to access the project locally by opening auctionweb.site in your browser. (If this still does not work you may have to restart your PC or reinstall ingress-nginx).

I have now added this step to the README and fixed the Kubernetes secrets.

**Comment by officeabg** [comment]
Hey, @JarrodMalkovic  this fixed it. Thank you!
I will open another issue with email spitting an error. I am sure that I am doing something wrong. Can you please DM me for some opportunity inquiries based on this project? I have my email on my profile page. Thanks for your quick reply
